# Generated by Django 5.0 on 2023-12-13 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='примьера в мире'),
        ),
    ]
