# Generated by Django 5.0 on 2023-12-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_world_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(max_length=130, unique=True),
        ),
    ]
