# Generated by Django 5.0 on 2023-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
